[tool.poetry]
name = "student-simulation"
version = "0.1.0"
description = ""
authors = ["danishmohammed <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
rich = "^10.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
